# Generated by Django 5.0.6 on 2026-08-18 09:29

import accounts.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism-familiya")),
                ('position', models.CharField(blank=True, help_text='Masalan: Frontend Dasturchi, Sotuvchi', max_length=150, verbose_name='Lavozimi')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name="Bo'limi")),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bir soatlik ish haqi miqdori', max_digits=12, verbose_name="Soatbay stavka (so'm)")),
                ('role', models.CharField(choices=[('HR', 'HR Admin'), ('EMPLOYEE', 'Xodim')], default='EMPLOYEE', max_length=10, verbose_name='Roli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin panelga kirish huquqi')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Ishga qabul qilingan sana')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
