# Generated by Django 5.0.6 on 2026-08-18 09:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Oy')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Jami ishlagan soatlar')),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Kelajakda xodim stavkasi o'zgarsa ham, o'sha oy uchun tarixiy stavka saqlanib qoladi.", max_digits=12, verbose_name='Hisoblangan paytdagi soatbay stavka')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name="Qo'lga tegadigan summa (Net Salary)")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'landimi")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan sana")),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Hisoblangan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Oylik hisob-kitob',
                'verbose_name_plural': 'Oylik hisob-kitoblar',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('employee', 'month', 'year'), name='unique_employee_month_year_payroll'),
        ),
    ]
